DROP TABLE IF EXISTS STOCK;

CREATE TABLE "STOCK" (
    "ID" VARCHAR2(10) PRIMARY KEY NOT NULL,
    "MODELO" VARCHAR2(40) NOT NULL,
    "COLOR" VARCHAR2(40) NOT NULL,
    "EXISTENCIAS" NUMBER NOT NULL
    );